window.BENCHMARK_DATA = {
  "entries": [
    {
      "commit": {
        "id": "59a87d58ba895cf337ea9e4dcf3063558b49d728",
        "message": "fix: HEAD 502 and no-keepalive stall in H2 sender",
        "url": "https://github.com/locustbaby/duotunnel/commit/59a87d58ba895cf337ea9e4dcf3063558b49d728"
      },
      "timestamp": "2026-04-09T09:53:18.394Z",
      "summary": {
        "totalRPS": 41986.55,
        "totalErr": 0.17,
        "totalRequests": 846659
      },
      "artifacts": {
        "trace_server": "https://locustbaby.github.io/duotunnel/bench/traces/59a87d5-24183635629-server.bin.gz",
        "trace_client": "https://locustbaby.github.io/duotunnel/bench/traces/59a87d5-24183635629-client.bin.gz"
      },
      "scenarios": [
        {
          "name": "ingress_http_get",
          "category": "basic",
          "p50": 0.63,
          "p95": 1.2,
          "rps": 37,
          "requests": 925,
          "err": 0,
          "protocol": "HTTP",
          "direction": "ingress",
          "includeInTotalRps": false
        },
        {
          "name": "ingress_http_post",
          "category": "basic",
          "p50": 0.56,
          "p95": 1.15,
          "rps": 23,
          "requests": 575,
          "err": 0,
          "protocol": "HTTP",
          "direction": "ingress",
          "includeInTotalRps": false
        },
        {
          "name": "egress_http_get",
          "category": "basic",
          "p50": 0.55,
          "p95": 1.1,
          "rps": 46,
          "requests": 1150,
          "err": 0,
          "protocol": "HTTP",
          "direction": "egress",
          "includeInTotalRps": false
        },
        {
          "name": "egress_http_post",
          "category": "basic",
          "p50": 0.56,
          "p95": 0.79,
          "rps": 36.48,
          "requests": 912,
          "err": 0,
          "protocol": "HTTP",
          "direction": "egress",
          "includeInTotalRps": false
        },
        {
          "name": "ws_ingress",
          "category": "basic",
          "p50": 2.06,
          "p95": 2.85,
          "rps": 10,
          "requests": 200,
          "err": 0,
          "protocol": "WS",
          "direction": "ingress",
          "includeInTotalRps": false
        },
        {
          "name": "grpc_health_ingress",
          "category": "basic",
          "p50": 1.19,
          "p95": 1.85,
          "rps": 20.05,
          "requests": 401,
          "err": 0,
          "protocol": "gRPC",
          "direction": "ingress",
          "includeInTotalRps": false
        },
        {
          "name": "grpc_echo_ingress",
          "category": "basic",
          "p50": 1.23,
          "p95": 1.9,
          "rps": 20.05,
          "requests": 401,
          "err": 0,
          "protocol": "gRPC",
          "direction": "ingress",
          "includeInTotalRps": false
        },
        {
          "name": "bidir_mixed",
          "category": "basic",
          "p50": 0.53,
          "p95": 0.8,
          "rps": 18.1,
          "requests": 362,
          "err": 0,
          "protocol": "HTTP",
          "direction": "bidir",
          "includeInTotalRps": false
        },
        {
          "name": "ingress_post_1k",
          "category": "body_size",
          "p50": 0.71,
          "p95": 1.94,
          "rps": 30.05,
          "requests": 601,
          "err": 0,
          "protocol": "HTTP",
          "direction": "ingress",
          "includeInTotalRps": false
        },
        {
          "name": "ingress_post_10k",
          "category": "body_size",
          "p50": 1.2,
          "p95": 2.59,
          "rps": 20,
          "requests": 400,
          "err": 0,
          "protocol": "HTTP",
          "direction": "ingress",
          "includeInTotalRps": false
        },
        {
          "name": "ingress_post_100k",
          "category": "body_size",
          "p50": 2.76,
          "p95": 3.69,
          "rps": 10,
          "requests": 200,
          "err": 0,
          "protocol": "HTTP",
          "direction": "ingress",
          "includeInTotalRps": false
        },
        {
          "name": "egress_post_10k",
          "category": "body_size",
          "p50": 1.13,
          "p95": 2.32,
          "rps": 20,
          "requests": 400,
          "err": 0,
          "protocol": "HTTP",
          "direction": "egress",
          "includeInTotalRps": false
        },
        {
          "name": "ws_multi_msg",
          "category": "basic",
          "p50": 44.37,
          "p95": 46.21,
          "rps": 5,
          "requests": 100,
          "err": 0,
          "protocol": "WS",
          "direction": "ingress",
          "includeInTotalRps": false
        },
        {
          "name": "grpc_large_payload",
          "category": "body_size",
          "p50": 1.14,
          "p95": 2.89,
          "rps": 15.05,
          "requests": 301,
          "err": 0,
          "protocol": "gRPC",
          "direction": "ingress",
          "includeInTotalRps": false
        },
        {
          "name": "grpc_high_qps",
          "category": "stress",
          "p50": 0.9,
          "p95": 1.77,
          "rps": 89.95,
          "requests": 1799,
          "err": 0,
          "protocol": "gRPC",
          "direction": "ingress",
          "includeInTotalRps": true
        },
        {
          "name": "ingress_3000qps",
          "category": "stress",
          "p50": 0.55,
          "p95": 2.05,
          "rps": 3000.05,
          "requests": 60001,
          "err": 0,
          "protocol": "HTTP",
          "direction": "ingress",
          "includeInTotalRps": true
        },
        {
          "name": "egress_3000qps",
          "category": "stress",
          "p50": 0.54,
          "p95": 1.91,
          "rps": 3000.05,
          "requests": 60001,
          "err": 0,
          "protocol": "HTTP",
          "direction": "egress",
          "includeInTotalRps": true
        },
        {
          "name": "ingress_multihost",
          "category": "stress",
          "p50": 0.56,
          "p95": 2.3,
          "rps": 3000.05,
          "requests": 60001,
          "err": 0,
          "protocol": "HTTP",
          "direction": "ingress",
          "includeInTotalRps": true
        },
        {
          "name": "egress_multihost",
          "category": "stress",
          "p50": 0.58,
          "p95": 2.16,
          "rps": 3000.1,
          "requests": 60002,
          "err": 0,
          "protocol": "HTTP",
          "direction": "egress",
          "includeInTotalRps": true
        },
        {
          "name": "ingress_8000qps (8k-q4)",
          "category": "stress",
          "p50": 5.34,
          "p95": 83.26,
          "rps": 7515.1,
          "requests": 150302,
          "err": 0,
          "protocol": "HTTP",
          "direction": "ingress",
          "includeInTotalRps": true
        },
        {
          "name": "egress_8000qps (8k-q4)",
          "category": "stress",
          "p50": 5.53,
          "p95": 79.65,
          "rps": 7556.95,
          "requests": 151139,
          "err": 0,
          "protocol": "HTTP",
          "direction": "egress",
          "includeInTotalRps": true
        },
        {
          "name": "ingress_multihost_8000qps (8k-q4)",
          "category": "stress",
          "p50": 3.29,
          "p95": 35.83,
          "rps": 7370.15,
          "requests": 147403,
          "err": 0.94,
          "protocol": "HTTP",
          "direction": "ingress",
          "includeInTotalRps": true
        },
        {
          "name": "egress_multihost_8000qps (8k-q4)",
          "category": "stress",
          "p50": 6.35,
          "p95": 95.97,
          "rps": 7454.15,
          "requests": 149083,
          "err": 0.01,
          "protocol": "HTTP",
          "direction": "egress",
          "includeInTotalRps": true
        },
        {
          "name": "ingress_3000qps",
          "category": "stress",
          "p50": 1.4,
          "p95": 59.99,
          "rps": 2901.7,
          "requests": 58034,
          "err": 0,
          "protocol": "HTTP",
          "direction": "ingress",
          "tunnel": "frp",
          "includeInTotalRps": true
        },
        {
          "name": "ingress_multihost",
          "category": "stress",
          "p50": 0.71,
          "p95": 3.34,
          "rps": 2999.4,
          "requests": 59988,
          "err": 0,
          "protocol": "HTTP",
          "direction": "ingress",
          "tunnel": "frp",
          "includeInTotalRps": true
        },
        {
          "name": "ingress_multihost_8000qps",
          "category": "stress",
          "p50": 44.52,
          "p95": 114.33,
          "rps": 5467,
          "requests": 109340,
          "err": 0,
          "protocol": "HTTP",
          "direction": "ingress",
          "tunnel": "frp",
          "includeInTotalRps": true
        }
      ]
    },
    {
      "commit": {
        "id": "756e8d113a09a0c9cbb7acc7a3e07b30a0b6b46f",
        "message": "fix: HEAD 502 and no-keepalive stall in H2 sender",
        "url": "https://github.com/locustbaby/duotunnel/commit/756e8d113a09a0c9cbb7acc7a3e07b30a0b6b46f"
      },
      "timestamp": "2026-04-09T09:57:56.729Z",
      "summary": {
        "totalRPS": 41212.2,
        "totalErr": 0.18,
        "totalRequests": 831175
      },
      "artifacts": {
        "trace_server": "https://locustbaby.github.io/duotunnel/bench/traces/756e8d1-24183846731-server.bin.gz",
        "trace_client": "https://locustbaby.github.io/duotunnel/bench/traces/756e8d1-24183846731-client.bin.gz"
      },
      "run_url": "https://github.com/locustbaby/duotunnel/actions/runs/24183846731",
      "scenarios": [
        {
          "name": "ingress_http_get",
          "category": "basic",
          "p50": 0.47,
          "p95": 0.89,
          "rps": 37,
          "requests": 925,
          "err": 0,
          "protocol": "HTTP",
          "direction": "ingress",
          "includeInTotalRps": false
        },
        {
          "name": "ingress_http_post",
          "category": "basic",
          "p50": 0.48,
          "p95": 0.82,
          "rps": 23,
          "requests": 575,
          "err": 0,
          "protocol": "HTTP",
          "direction": "ingress",
          "includeInTotalRps": false
        },
        {
          "name": "egress_http_get",
          "category": "basic",
          "p50": 0.45,
          "p95": 0.91,
          "rps": 46,
          "requests": 1150,
          "err": 0,
          "protocol": "HTTP",
          "direction": "egress",
          "includeInTotalRps": false
        },
        {
          "name": "egress_http_post",
          "category": "basic",
          "p50": 0.45,
          "p95": 0.55,
          "rps": 36.48,
          "requests": 912,
          "err": 0,
          "protocol": "HTTP",
          "direction": "egress",
          "includeInTotalRps": false
        },
        {
          "name": "ws_ingress",
          "category": "basic",
          "p50": 1.6,
          "p95": 2.23,
          "rps": 10.05,
          "requests": 201,
          "err": 0,
          "protocol": "WS",
          "direction": "ingress",
          "includeInTotalRps": false
        },
        {
          "name": "grpc_health_ingress",
          "category": "basic",
          "p50": 0.92,
          "p95": 1.45,
          "rps": 20.05,
          "requests": 401,
          "err": 0,
          "protocol": "gRPC",
          "direction": "ingress",
          "includeInTotalRps": false
        },
        {
          "name": "grpc_echo_ingress",
          "category": "basic",
          "p50": 0.92,
          "p95": 1.64,
          "rps": 20.05,
          "requests": 401,
          "err": 0,
          "protocol": "gRPC",
          "direction": "ingress",
          "includeInTotalRps": false
        },
        {
          "name": "bidir_mixed",
          "category": "basic",
          "p50": 0.42,
          "p95": 0.55,
          "rps": 18.1,
          "requests": 362,
          "err": 0,
          "protocol": "HTTP",
          "direction": "bidir",
          "includeInTotalRps": false
        },
        {
          "name": "ingress_post_1k",
          "category": "body_size",
          "p50": 0.53,
          "p95": 1.88,
          "rps": 30.05,
          "requests": 601,
          "err": 0,
          "protocol": "HTTP",
          "direction": "ingress",
          "includeInTotalRps": false
        },
        {
          "name": "ingress_post_10k",
          "category": "body_size",
          "p50": 0.99,
          "p95": 2.11,
          "rps": 20,
          "requests": 400,
          "err": 0,
          "protocol": "HTTP",
          "direction": "ingress",
          "includeInTotalRps": false
        },
        {
          "name": "ingress_post_100k",
          "category": "body_size",
          "p50": 2.49,
          "p95": 3.35,
          "rps": 10,
          "requests": 200,
          "err": 0,
          "protocol": "HTTP",
          "direction": "ingress",
          "includeInTotalRps": false
        },
        {
          "name": "egress_post_10k",
          "category": "body_size",
          "p50": 0.94,
          "p95": 2.05,
          "rps": 20.05,
          "requests": 401,
          "err": 0,
          "protocol": "HTTP",
          "direction": "egress",
          "includeInTotalRps": false
        },
        {
          "name": "ws_multi_msg",
          "category": "basic",
          "p50": 43.96,
          "p95": 45.78,
          "rps": 5.05,
          "requests": 101,
          "err": 0,
          "protocol": "WS",
          "direction": "ingress",
          "includeInTotalRps": false
        },
        {
          "name": "grpc_large_payload",
          "category": "body_size",
          "p50": 0.94,
          "p95": 2.61,
          "rps": 15.05,
          "requests": 301,
          "err": 0,
          "protocol": "gRPC",
          "direction": "ingress",
          "includeInTotalRps": false
        },
        {
          "name": "grpc_high_qps",
          "category": "stress",
          "p50": 0.7,
          "p95": 1.49,
          "rps": 90,
          "requests": 1800,
          "err": 0,
          "protocol": "gRPC",
          "direction": "ingress",
          "includeInTotalRps": true
        },
        {
          "name": "ingress_3000qps",
          "category": "stress",
          "p50": 0.48,
          "p95": 1.85,
          "rps": 3000.05,
          "requests": 60001,
          "err": 0,
          "protocol": "HTTP",
          "direction": "ingress",
          "includeInTotalRps": true
        },
        {
          "name": "egress_3000qps",
          "category": "stress",
          "p50": 0.48,
          "p95": 1.82,
          "rps": 3000,
          "requests": 60000,
          "err": 0,
          "protocol": "HTTP",
          "direction": "egress",
          "includeInTotalRps": true
        },
        {
          "name": "ingress_multihost",
          "category": "stress",
          "p50": 0.5,
          "p95": 2.08,
          "rps": 3000.05,
          "requests": 60001,
          "err": 0,
          "protocol": "HTTP",
          "direction": "ingress",
          "includeInTotalRps": true
        },
        {
          "name": "egress_multihost",
          "category": "stress",
          "p50": 0.5,
          "p95": 2.15,
          "rps": 3000.05,
          "requests": 60001,
          "err": 0,
          "protocol": "HTTP",
          "direction": "egress",
          "includeInTotalRps": true
        },
        {
          "name": "ingress_8000qps (8k-q4)",
          "category": "stress",
          "p50": 31.97,
          "p95": 104.75,
          "rps": 7337.15,
          "requests": 146743,
          "err": 0,
          "protocol": "HTTP",
          "direction": "ingress",
          "includeInTotalRps": true
        },
        {
          "name": "egress_8000qps (8k-q4)",
          "category": "stress",
          "p50": 12.3,
          "p95": 99.19,
          "rps": 7386.9,
          "requests": 147738,
          "err": 0,
          "protocol": "HTTP",
          "direction": "egress",
          "includeInTotalRps": true
        },
        {
          "name": "ingress_multihost_8000qps (8k-q4)",
          "category": "stress",
          "p50": 10.16,
          "p95": 35.12,
          "rps": 7210.95,
          "requests": 144219,
          "err": 1.05,
          "protocol": "HTTP",
          "direction": "ingress",
          "includeInTotalRps": true
        },
        {
          "name": "egress_multihost_8000qps (8k-q4)",
          "category": "stress",
          "p50": 36.03,
          "p95": 134.85,
          "rps": 7187.05,
          "requests": 143741,
          "err": 0.01,
          "protocol": "HTTP",
          "direction": "egress",
          "includeInTotalRps": true
        },
        {
          "name": "ingress_3000qps",
          "category": "stress",
          "p50": 1.74,
          "p95": 53.37,
          "rps": 2925.8,
          "requests": 58516,
          "err": 0,
          "protocol": "HTTP",
          "direction": "ingress",
          "tunnel": "frp",
          "includeInTotalRps": true
        },
        {
          "name": "ingress_multihost",
          "category": "stress",
          "p50": 0.55,
          "p95": 2.6,
          "rps": 2998.65,
          "requests": 59973,
          "err": 0,
          "protocol": "HTTP",
          "direction": "ingress",
          "tunnel": "frp",
          "includeInTotalRps": true
        },
        {
          "name": "ingress_multihost_8000qps",
          "category": "stress",
          "p50": 30.13,
          "p95": 94.53,
          "rps": 6351.45,
          "requests": 127029,
          "err": 0,
          "protocol": "HTTP",
          "direction": "ingress",
          "tunnel": "frp",
          "includeInTotalRps": true
        }
      ]
    }
  ]
};
