server:
  tunnel_port: 10086
  h2_single_authority: true
  log_level: "debug"
  trace_enabled: false
  database_url: "sqlite://./data/duotunnel.db?mode=rwc"

  tcp:
    nodelay: true

  quic:
    max_concurrent_streams: 1000
    keepalive_secs: 20
    idle_timeout_secs: 60

  http_pool:
    idle_timeout_secs: 90
    max_idle_per_host: 10

  proxy_buffers:
    peek_buf_size: 16384

  pki:
    cert_cache_ttl_secs: 3600

server_egress_upstream:
  upstreams:
    backend:
      servers:
        - address: "https://www.google.com"
          resolve: true
      lb_policy: "round_robin"

  rules:
    vhost:
      - match_host: "wss.localtest.com"
        action_upstream: "backend"

tunnel_management:
  server_ingress_routing:
    listeners:
      - port: 8001
        mode: http
        vhost:
          - match_host: "wss.localtest.com"
            action_client_group: "group-a"
            action_proxy_name: "grpc_service"
          - match_host: "harbor.example.com"
            action_client_group: "group-a"
            action_proxy_name: "google_service"
          - match_host: "test.local"
            action_client_group: "group-a"
            action_proxy_name: "http_service"
          - match_host: "www2.localtest.com"
            action_client_group: "group-b"
            action_proxy_name: "local_service"

      - port: 50051
        mode: tcp
        action_client_group: "group-a"
        action_proxy_name: "grpc_service"

  client_configs:
    groups:
      group-a:
        config_version: "v1.0.0"
        upstreams:
          grpc_service:
            servers:
              - address: "https://grpc-echo.semior.dev:443"
                resolve: true
            lb_policy: "round_robin"

          google_service:
            servers:
              - address: "www.google.com:443"
                resolve: true
            lb_policy: "round_robin"

          http_service:
            servers:
              - address: "127.0.0.1:8080"
                resolve: false
            lb_policy: "round_robin"

          echo_beeceptor:
            servers:
              - address: "echo.free.beeceptor.com:443"
                resolve: true
            lb_policy: "round_robin"

          wss_service:
            servers:
              - address: "wss://echo.websocket.org"
                resolve: false
            lb_policy: "round_robin"

      group-b:
        config_version: "v1.0.0"
        upstreams:
          local_service:
            servers:
              - address: "127.0.0.1:9100"
                resolve: false
            lb_policy: "round_robin"
